feat(views): views for relation resolving can now be created and all entries can be returned via api
interim

first proper working version for views

feat(views): created controller, service, repository layer

feat(relations): removed mirror fields, added for each collection a name which will be used in views for mapping, fixed test

feat(relations): added mapping for item values

fix(views): changed to view instead of materialized view, fixed grouping and added more complex test

error: enabled nested aggregates which are not suppoerted in sql

fix(views): relations are now properly aggregated and kartesian prodcuts are filtered out